branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-my-application
global:
  application_name: my-dummy-app-my-application
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  sc: git


