branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-Dummyapp4-env
global:
  application_name: Dummyapp4
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux/4.7.0 
  default_region: us-west-2
  sc: git


