branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-Dummyapp3-env
global:
  application_name: Dummyapp3
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.5 running on 64bit Amazon Linux/2.8.6
  default_region: us-west-2
  sc: git


